### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by simahawk** [OCA/odoo-test-helper#14]
@sebastienbeau can you do a new release?

Also, please have a look at pending PRs :pray:

**Comment by sebastienbeau** [comment]
maybe it's time to move this to OCA @sbidoul ?

**Comment by sbidoul** [comment]
:+1:

**Comment by sebastienbeau** [comment]
Note : there is no more auto-publish as travis CI have been shutdown, so let's move to github workflow + OCA !

**Comment by sebastienbeau** [comment]
I transfers the projet to OCA owner (I do the same on pipy) ? then does some of you have time for moving to github workflow ?

**Comment by sbidoul** [comment]
I'm unlikely to have time for this soon.

**Comment by simahawk** [comment]
@sbidoul what's the right way to handle this? 
Something like https://github.com/OCA/openupgradelib/commit/77513de21fb87ed367cb26b4bbe45faa78da5bba ?

**Comment by sbidoul** [comment]
@simahawk yes, that is my preferred approach

- setuptools_scm to get the version from git tags
- pypa/build for building the wheel and sdist
- pypa/gh-action-pypi-publish to publish from a GitHub action

The one just need to tag the release to publish.

**Comment by sebastienbeau** [comment]
I have sent an invitation for the transfer of ownership on pipy

**Comment by sbidoul** [comment]
@simahawk you don't need this part https://github.com/OCA/openupgradelib/blob/master/openupgradelib/__init__.py

**Comment by sbidoul** [comment]
Accepted on PyPI, and I have added the PYPI_TOKEN secret in the repo so you can use it in the publish action.

**Comment by sebastienbeau** [comment]
Thanks !

**Comment by simahawk** [comment]
@sbidoul cool, tnx. I'll have a look later this week

**Comment by simahawk** [comment]
yoohooo https://pypi.org/project/odoo-test-helper/2.0.0
