### ISSUE TITLE
Are we sure there's no left over?

### ISSUE THREAD

**Issue by simahawk** [OCA/odoo-test-helper#3]
I'm testing this here https://travis-ci.org/github/OCA/website-cms/jobs/676905184
and the log says:

`2020-04-19 15:34:58,774 23433 ERROR cms13_test odoo.modules.registry: Model fake.model has no table. `

@sebastienbeau Am I missing anything? My previous implementation w/ model mixin had no issue.

I think the issue is here https://github.com/akretion/odoo-test-helper/blob/master/odoo_test_helper/fake_model_loader.py#L75 because you reload the module but this should not be needed if the model is not an existing one as `res.partner` in your case.
What do you think?

**Comment by simahawk** [comment]
Likely fixed here https://github.com/akretion/odoo-test-helper/pull/1/commits/2dd030e4a21e38120120c061f121334085562825

**Comment by sebastienbeau** [comment]
Now it work on all odoo version : https://github.com/akretion/odoo-test-helper/pull/9
